# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      name: default
    steps:

      - script: echo "L0 Tests"
        displayName: L0 tests

      - script: echo "L1 Tests"
        displayName: L0 tests

      - script: echo "Publish test results"
        displayName: Publish test results

      - script: echo "Update artifacts"
        displayName: Update artifacts

      - script: echo "Publish to artifact services"
        displayName: Publish to artifact services

- stage: Staging
  displayName: Staging
  dependsOn: [Build]
  jobs:
  - deployment: job1
    environment: environment-test
    pool: default
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "echo Hello, world!"
            displayName: 'Run a one-line script'
  - deployment: job2
    environment: environment-staging2
    pool: default
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Hello, world!2"
            displayName: 'Run a one-line script2'

- stage: Prod
  displayName: Prod
  dependsOn: [Staging]
  jobs:
  - job: Deploy
    displayName: Deploy to kubernetes
    pool:
      name: default
    steps:
    - checkout: none
    - script: echo "Deploy project1"
      displayName: Deploy
